jobs:
  build_and_tests:
    name: Build and Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
    - continue-on-error: true
      name: Setup Go
      uses: actions/setup-go@44e221478fc6847752e5c574fc7a7b3247b00fbf
      with:
        go-version: '1.21'
    - continue-on-error: true
      name: Run Tests
      run: 'cd cicd

        go test ./...

        '
    timeout-minutes: 5
  check_formatting:
    name: Go FMT
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
    - continue-on-error: true
      name: Setup Go
      uses: actions/setup-go@44e221478fc6847752e5c574fc7a7b3247b00fbf
      with:
        go-version: '1.21'
    - continue-on-error: true
      name: Run Fmt
      run: "cd cicd\nif [[ $(go fmt ./...) != \"\" ]]; then\n  echo 'There were formatting\
        \ violations'\n  exit 1\nfi\n"
    timeout-minutes: 5
name: Go PR
on:
  repository_dispatch:
    types: trigger-ga___go-pr.yml
permissions: read-all
