env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.shade=error
jobs:
  checkstyle_check:
    name: Checkstyle
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
    - continue-on-error: true
      id: setup-env
      name: Setup Environment
      uses: ./.github/actions/setup-env
    - continue-on-error: true
      name: Run Checkstyle
      run: ./cicd/run-checkstyle --changed-files="${{ steps.setup-env.outputs.changed-files
        }}"
    timeout-minutes: 10
  java_build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
    - continue-on-error: true
      id: setup-env
      name: Setup Environment
      uses: ./.github/actions/setup-env
    - continue-on-error: true
      name: Run Build
      run: ./cicd/run-build --changed-files="${{ steps.setup-env.outputs.changed-files
        }}"
    - continue-on-error: true
      name: Cleanup Java Environment
      uses: ./.github/actions/cleanup-java-env
    timeout-minutes: 60
  java_integration_smoke_tests_templates:
    name: Dataflow Templates Integration Smoke Tests
    needs:
    - spotless_check
    - checkstyle_check
    - java_build
    - java_unit_tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
    - continue-on-error: true
      id: setup-env
      name: Setup Environment
      uses: ./.github/actions/setup-env
    - continue-on-error: true
      name: Run Integration Smoke Tests
      run: './cicd/run-it-smoke-tests \

        --changed-files="${{ steps.setup-env.outputs.changed-files }}" \

        --it-region="us-central1" \

        --it-project="cloud-teleport-testing" \

        --it-artifact-bucket="cloud-teleport-testing-it-gitactions" \

        --it-private-connectivity="datastream-private-connect-us-central1"

        '
    - continue-on-error: true
      if: always()
      name: Upload Smoke Tests Report
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: surefire-test-results
        path: '**/surefire-reports/TEST-*.xml'
        retention-days: 1
    - continue-on-error: true
      name: Cleanup Java Environment
      uses: ./.github/actions/cleanup-java-env
    timeout-minutes: 60
  java_integration_tests_templates:
    name: Dataflow Templates Integration Tests
    needs:
    - java_integration_smoke_tests_templates
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
    - continue-on-error: true
      id: setup-env
      name: Setup Environment
      uses: ./.github/actions/setup-env
    - continue-on-error: true
      name: Run Integration Tests
      run: './cicd/run-it-tests \

        --changed-files="${{ steps.setup-env.outputs.changed-files }}" \

        --it-region="us-central1" \

        --it-project="cloud-teleport-testing" \

        --it-artifact-bucket="cloud-teleport-testing-it-gitactions" \

        --it-private-connectivity="datastream-private-connect-us-central1"

        '
    - continue-on-error: true
      if: always()
      name: Upload Integration Tests Report
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: surefire-test-results
        path: '**/surefire-reports/TEST-*.xml'
        retention-days: 1
    - continue-on-error: true
      name: Cleanup Java Environment
      uses: ./.github/actions/cleanup-java-env
    timeout-minutes: 180
  java_load_tests_templates:
    if: contains(github.event.pull_request.labels.*.name, 'run-load-tests')
    name: Dataflow Templates Load Tests
    needs:
    - spotless_check
    - checkstyle_check
    - java_build
    - java_unit_tests
    - java_integration_tests_templates
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
    - continue-on-error: true
      id: setup-env
      name: Setup Environment
      uses: ./.github/actions/setup-env
    - continue-on-error: true
      name: Run Load Tests
      run: './cicd/run-load-tests \

        --changed-files="${{ steps.setup-env.outputs.changed-files }}" \

        --it-region="us-central1" \

        --it-project="cloud-teleport-testing" \

        --it-artifact-bucket="cloud-teleport-testing-it-gitactions" \

        --it-private-connectivity="datastream-private-connect-us-central1"

        '
    - continue-on-error: true
      name: Cleanup Java Environment
      uses: ./.github/actions/cleanup-java-env
    timeout-minutes: 600
  java_unit_tests:
    name: Unit Tests
    needs:
    - java_build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
    - continue-on-error: true
      id: setup-env
      name: Setup Environment
      uses: ./.github/actions/setup-env
    - continue-on-error: true
      name: Run Unit Tests
      run: ./cicd/run-unit-tests --changed-files="${{ steps.setup-env.outputs.changed-files
        }}"
    - continue-on-error: true
      if: always()
      name: Upload Unit Tests Report
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: surefire-test-results
        path: '**/surefire-reports/TEST-*.xml'
        retention-days: 1
    - continue-on-error: true
      name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        files: target/site/jacoco-aggregate/jacoco.xml
        slug: GoogleCloudPlatform/DataflowTemplates
        token: ${{ secrets.CODECOV_TOKEN }}
    - continue-on-error: true
      name: Cleanup Java Environment
      uses: ./.github/actions/cleanup-java-env
    timeout-minutes: 60
  spotless_check:
    name: Spotless
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
    - continue-on-error: true
      id: setup-env
      name: Setup Environment
      uses: ./.github/actions/setup-env
    - continue-on-error: true
      name: Run Spotless
      run: ./cicd/run-spotless --changed-files="${{ steps.setup-env.outputs.changed-files
        }}"
    timeout-minutes: 10
name: Java PR
on:
  repository_dispatch:
    types: trigger-ga___java-pr.yml
permissions: read-all
