jobs:
  load_tests:
    name: Dataflow Templates Load tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: setup-java-env
      name: Setup Environment
      uses: ./.github/actions/setup-java-env
    - continue-on-error: true
      id: variables
      name: Get Host IP
      run: echo "hostIP=$(gcloud compute instances list | grep $(hostname) | awk '{print
        $4; exit}' )" >> $GITHUB_OUTPUT
    - continue-on-error: true
      env:
        HOST_IP: ${{ steps.variables.outputs.hostIP }}
      name: Run load tests with Maven
      run: 'mvn test -PtemplatesLoadTests \

        -Dproject=apache-beam-testing \

        -DartifactBucket=gs://apache-beam-testing-pranavbhandari \

        -DhostIp=${HOST_IP} \

        -DprivateConnectivity="datastream-private-connect-us-central1" \

        -DexportProject=cloud-teleport-testing \

        -DexportDataset=performance_tests \

        -DexportTable=template_performance_metrics -e -fae

        '
    - continue-on-error: true
      if: always()
      name: Upload Load Tests Report
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: surefire-test-results
        path: '**/surefire-reports/TEST-*.xml'
        retention-days: 1
    - continue-on-error: true
      name: Cleanup Java Environment
      uses: ./.github/actions/cleanup-java-env
    timeout-minutes: 2880
name: Load Tests
on:
  repository_dispatch:
    types: trigger-ga___load-tests.yml
permissions: read-all
