jobs:
  cache_dependencies:
    name: Cache Java Dependencies
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ github.event_name == 'workflow_dispatch' }}
      name: Set Manual Key
      run: 'echo "$(date -u --date=''${{ inputs.days }} days'' +%Y%m%d)" >> $GITHUB_ENV

        '
    - continue-on-error: true
      if: ${{ github.event_name != 'workflow_dispatch' }}
      name: Set Empty Key
      run: 'echo "CACHE_KEY=''''" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
    - continue-on-error: true
      id: setup-java
      name: Setup Java
      uses: ./.github/actions/setup-java-env
      with:
        cache-key: ${{ env.CACHE_KEY }}
    - continue-on-error: true
      if: ${{ steps.setup-java.outputs.cache-hit != 'true' || github.event_name ==
        'pull_request' }}
      name: Resolve Dependencies
      run: "mvn -B clean install \\\n  -Dmaven.test.skip \\\n  -Dcheckstyle.skip \\\
        \n  -Djib.skip \\\n  -Dmdep.analyze.skip \\\n  -Dspotless.check.skip\n"
    - continue-on-error: true
      name: Cleanup Java Environment
      uses: ./.github/actions/cleanup-java-env
    timeout-minutes: 60
name: Prepare Java Cache
on:
  repository_dispatch:
    types: trigger-ga___prepare-java-cache.yml
permissions: read-all
