jobs:
  release:
    name: Create Release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Get releaser identity
      run: 'git config --global user.name ''${{github.actor}}''

        git config --global user.email ''${{github.actor}}@users.noreply.github.com''

        '
    - continue-on-error: true
      env:
        CANDIDATE_NAME: ${{ inputs.candidateName }}
      id: variables
      name: Declare release branch name and tag name
      run: 'echo "releaseBranchName=release_${CANDIDATE_NAME,,}" >> $GITHUB_OUTPUT

        echo "tagName=${CANDIDATE_NAME^^}" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      with:
        fetch-depth: 0
        token: ${{ secrets.RELEASE_TOKEN }}
    - continue-on-error: true
      env:
        BRANCH_COMMIT: ${{ inputs.branchCommit }}
        RELEASE_BRANCH_NAME: ${{ steps.variables.outputs.releaseBranchName }}
      name: Create release branch
      run: git checkout -b $RELEASE_BRANCH_NAME $BRANCH_COMMIT
    - continue-on-error: true
      env:
        CHERRYPICK_COMMITS: ${{ inputs.cherrypickCommits }}
      name: Cherry pick commits
      run: "commits=$(echo $CHERRYPICK_COMMITS | tr \",\" \"\\n\")\nfor commit in\
        \ $commits\ndo\n  echo \"Cherry picking $commit.\"\n  git cherry-pick $commit\n\
        done\n"
    - continue-on-error: true
      env:
        RELEASE_BRANCH_NAME: ${{ steps.variables.outputs.releaseBranchName }}
        TAG_NAME: ${{ steps.variables.outputs.tagName }}
      name: Add tag to most recent commit
      run: 'DATE=$(date -d"next-monday - 1week" +''%Y-%m-%d'')

        T_COMMIT=$(git log -n 1 $RELEASE_BRANCH_NAME --pretty=format:''%H'')

        git tag -a $TAG_NAME -m "Release week of $DATE" $T_COMMIT

        '
    - continue-on-error: true
      id: setup-env
      name: Setup Environment
      uses: ./.github/actions/setup-env
    - continue-on-error: true
      name: Run Build
      run: ./cicd/run-build --changed-files="pom.xml"
    - continue-on-error: true
      name: Run Unit Tests
      run: ./cicd/run-unit-tests --changed-files="pom.xml"
    - continue-on-error: true
      name: Run Integration Smoke Tests
      run: './cicd/run-it-smoke-tests \

        --changed-files="pom.xml" \

        --it-region="us-central1" \

        --it-project="cloud-teleport-testing" \

        --it-artifact-bucket="cloud-teleport-testing-it-gitactions" \

        --it-private-connectivity="datastream-private-connect-us-central1" \

        --it-release=true

        '
    - continue-on-error: true
      name: Run Integration Tests
      run: './cicd/run-it-tests \

        --changed-files="pom.xml" \

        --it-region="us-central1" \

        --it-project="cloud-teleport-testing" \

        --it-artifact-bucket="cloud-teleport-testing-it-gitactions" \

        --it-private-connectivity="datastream-private-connect-us-central1" \

        --it-release=true

        '
    - continue-on-error: true
      if: always()
      name: Upload Tests Report
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: surefire-test-results
        path: '**/surefire-reports/TEST-*.xml'
        retention-days: 1
    - continue-on-error: true
      env:
        CANDIDATE_NAME: ${{ inputs.candidateName }}
      name: Create artifacts and push
      run: 'mvn verify -PtemplatesRelease \

        -DprojectId="dataflow-templates" \

        -DbucketName="dataflow-templates-staging" \

        -DlibrariesBucketName="dataflow-templates-libraries" \

        -DstagePrefix="${CANDIDATE_NAME}" \

        -Dmaven.test.skip -T8 -e

        '
    - continue-on-error: true
      name: Push tags
      run: 'git push -u origin --tags

        '
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{ steps.variables.outputs.tagName }}
      name: Release
      run: 'gh release create $TAG_NAME --title "Dataflow Templates $TAG_NAME" --notes
        ""

        '
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
permissions:
  contents: write
